pipeline {
    agent any
    tools {
        maven "MAVEN"
    }
    environment {
        ARTIFACT_NAME = 'Ehealth-B-1.0-SNAPSHOT.jar'  // Remplace par le nom correct du fichier généré
        ARTIFACT_PATH = 'Backend/Ehealth-B/target'   // Chemin vers l'artefact
    }
    stages {
        stage('Build') {
            steps {
                echo 'Build Start'
                
                // Cloner le repo contenant le code source
                checkout scmGit(branches: [[name: '*/ciPipeline']], 
                    extensions: [], 
                    userRemoteConfigs: [[credentialsId: 'd160d1c6-6304-4ba3-b050-7d418e127b85', 
                    url: 'https://github.com/E-Health-Organization/E-health-Backend.git']]
                )
                
                // Build avec Maven sans exécuter les tests
                sh 'cd Backend/Ehealth-B && mvn -B -DskipTests clean package'
                
                echo 'Build Finished'
            }
        }

        stage('Copy Artifact to Another Repo') {
            steps {
                script {
                    echo 'Cloning the target repository...'
                    
                    // Cloner le deuxième repo (où tu veux stocker l'artefact)
                    sh '''
                    git clone https://github.com/E-Health-Organization/Artifact_Ehealth_Backend.git target-repo
                    '''

                    echo 'Copying artifact...'
                    
                    // Copier l'artefact dans le dépôt cible
                    sh '''
                    cp ${ARTIFACT_PATH}/${ARTIFACT_NAME} target-repo/
                    cd target-repo
                    git config user.email "aymar.hakizimana@gmail.com"
                    git config user.name "HaAymar"
                    git add ${ARTIFACT_NAME}
                    git commit -m "Adding new build artifact"
                    git push https://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@github.com/E-Health-Organization/Artifact_Ehealth_Backend.git
                    '''

                    echo 'Artifact copied successfully!'
                }
            }
        }
    }
}
